- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}   # 3.106.116.106
    username: ec2-user
    key: ${{ secrets.EC2_SSH_KEY }}
    port: 22
    debug: true
    script: |
      cd /home/ec2-user/contractx
      git pull origin production
      docker compose down
      docker compose build
      docker compose up -d
